spring.datasource:
  url: jdbc:postgresql://localhost:5432/process-engine
#  url: jdbc:mysql://portainer.camunda.loc:3306/process-engine
#  url: jdbc:oracle:thin:@portainer.camunda.loc:1521:ORCL
  username: camunda
  password: camunda
  driver-class-name: org.postgresql.Driver
#  driver-class-name: com.mysql.jdbc.Driver
#  driver-class-name: oracle.jdbc.OracleDriver

camunda:
  bpm:
    filter:
      create: All
    job-execution:
      core-pool-size: 10
    admin-user:
      id: demo
      password: demo

